### ISSUE TITLE
Tree ordering: 'Test' before 'Run'

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#84] opened 2017-11-28 13:22 UTC
dmake used to `test` a service before `run`ning it. Since a few month it's not the case anymore.

Example for worker-nn:
```
## Testing App ##
- run_link @ links/vulcain/rabbitmq
- run_link @ links/vulcain/redis
- run @ vulcain/worker-nn
- test @ vulcain/developers
- run @ vulcain/worker-nn--140069730953104
- test @ vulcain/worker-nn
- test @ vulcain/api
```

In this example, a job is running forever in Jenkins because it's waiting for the worker to boot, which does not happen for some reason and might have been avoided by testing first.

**Comment by thomas-riccardi** [comment] 2019-01-18 10:09
Closing as duplicate of #243

**Closed by thomas-riccardi** 2019-01-18 10:09 UTC
